version: "3"
services:
  jupyter-colab:
    build:
      context: .
    ports:
      - "8888:8888"
    volumes:
      - ~/ai:/mnt/ai
    restart: always
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
        #    deploy:
        #      resources:
        #        reservations:
        #          devices:
        #            - driver: nvidia
        #              count: 1
        #              capabilities: [gpu]
